### ISSUE TITLE
Unable to download aar when using with another private jitpack library.

### ISSUE THREAD

**Issue by disparate** [phrase/android-sdk-example#4]
Hello, I've encountered following issue when using phraseapp OTA library for my project.
Sometimes gradle is unable to download aar for the dependency (it returns 401 Unauthorized) if I also use another private jitpack library in the project.
When I use phraseapp lib alone it works perfect and always download the dependency during gradle sync.
I created an issue on jitpack's repo with detailed description (jitpack/jitpack.io#3759) , but I'm not sure if the problem is on their side. Maybe you can take a look on it?

**Comment by theSoenke** [comment]
Discussion in https://github.com/phrase/phraseapp-android/issues/2
