### ISSUE TITLE
App not work when change appcompat version to 1.2.0

### ISSUE THREAD

**Issue by thaworn-li** [phrase/android-sdk-example#5]
I try to change appcompat 1.2.0 instead of 1.1.0 but it doesn't work.
I'm not sure it's about this issue below. Please verify it.
Our company has a plan to use this service.

https://stackoverflow.com/questions/55265834/change-locale-not-work-after-migrate-to-androidx

**Comment by theSoenke** [comment]
Hey @thaworn-li, I'm sorry for my late response. We've released a new major version 3.x of the SDK, which should resolve all issues with appcompat 1.2.0.
